import type { FishListing, Purchase } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const initialFishListings: FishListing[] = [
  {
    id: '1',
    sellerId: 'seller1',
    name: 'Tuna',
    weight: 50,
    price: 800,
    freshness: 'Just Caught',
    imageUrl: 'https://images.unsplash.com/photo-1516741539888-96b4c96adf0c?q=80&w=600&auto=format&fit=crop',
    imageHint: 'tuna fish',
    dateListed: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    id: '2',
    sellerId: 'seller2',
    name: 'Salmon',
    weight: 30,
    price: 1200,
    freshness: '1-2 Days',
    imageUrl: 'https://images.unsplash.com/photo-1510018572596-e40e2619b412?q=80&w=600&auto=format&fit=crop',
    imageHint: 'salmon fish',
    dateListed: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
  },
  {
    id: '3',
    sellerId: 'seller1',
    name: 'Sardine',
    weight: 100,
    price: 250,
    freshness: 'Just Caught',
    imageUrl: 'https://images.unsplash.com/photo-1651276950299-44714b8677f9?q=80&w=600&auto=format&fit=crop',
    imageHint: 'sardines fish',
    dateListed: new Date().toISOString(),
  },
  {
    id: '4',
    sellerId: 'seller3',
    name: 'Mackerel',
    weight: 80,
    price: 400,
    freshness: '1-2 Days',
    imageUrl: 'https://images.unsplash.com/photo-1554071407-1fb7259a9118?q=80&w=600&auto=format&fit=crop',
    imageHint: 'mackerel fish',
    dateListed: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    id: '5',
    sellerId: 'seller2',
    name: 'Pomfret',
    weight: 40,
    price: 950,
    freshness: '3+ Days',
    imageUrl: 'https://images.unsplash.com/photo-1760560749248-308061f48097?q=80&w=600&auto=format&fit=crop',
    imageHint: 'pomfret fish',
    dateListed: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
  },
  {
    id: '6',
    sellerId: 'seller1',
    name: 'Rohu',
    weight: 75,
    price: 350,
    freshness: 'Just Caught',
    imageUrl: 'https://images.unsplash.com/photo-1564677877393-2dbc65af5e41?q=80&w=600&auto=format&fit=crop',
    imageHint: 'rohu fish',
    dateListed: new Date().toISOString(),
  },
  {
    id: '7',
    sellerId: 'seller3',
    name: 'Catla',
    weight: 60,
    price: 320,
    freshness: '1-2 Days',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1695299693952-4113f5682414?q=80&w=600&auto=format&fit=crop',
    imageHint: 'catla fish',
    dateListed: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
  },
  {
    id: '8',
    sellerId: 'seller2',
    name: 'Hilsa',
    weight: 25,
    price: 1500,
    freshness: 'Just Caught',
    imageUrl: 'https://images.unsplash.com/photo-1668532696872-dc5fe74a47f7?q=80&w=600&auto=format&fit=crop',
    imageHint: 'hilsa fish',
    dateListed: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    id: '9',
    sellerId: 'seller1',
    name: 'Kingfish (Surmai)',
    weight: 35,
    price: 1100,
    freshness: '1-2 Days',
    imageUrl: 'https://images.unsplash.com/photo-1625369909585-0f9fcbc3d79a?q=80&w=600&auto=format&fit=crop',
    imageHint: 'kingfish surmai',
    dateListed: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    id: '10',
    sellerId: 'seller3',
    name: 'Bombay Duck',
    weight: 90,
    price: 200,
    freshness: '3+ Days',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1718204043243-ca3666657158?q=80&w=600&auto=format&fit=crop',
    imageHint: 'bombay duck',
    dateListed: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString(),
  },
  {
    id: '11',
    sellerId: 'seller2',
    name: 'Anchovy',
    weight: 120,
    price: 180,
    freshness: 'Just Caught',
    imageUrl: 'https://images.unsplash.com/photo-1560166241-0fca91a3d29a?q=80&w=600&auto=format&fit=crop',
    imageHint: 'anchovy fish',
    dateListed: new Date().toISOString(),
  },
  {
    id: '12',
    sellerId: 'seller1',
    name: 'Red Snapper',
    weight: 45,
    price: 750,
    freshness: '1-2 Days',
    imageUrl: 'https://images.unsplash.com/photo-1673912401852-7d97385c293b?q=80&w=600&auto=format&fit=crop',
    imageHint: 'red snapper',
    dateListed: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
  },
  {
    id: '13',
    sellerId: 'seller3',
    name: 'Grouper',
    weight: 55,
    price: 850,
    freshness: 'Just Caught',
    imageUrl: 'https://images.unsplash.com/photo-1537319064867-3163638edd4b?q=80&w=600&auto=format&fit=crop',
    imageHint: 'grouper fish',
    dateListed: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    id: '14',
    sellerId: 'seller2',
    name: 'Cod',
    weight: 65,
    price: 900,
    freshness: '3+ Days',
    imageUrl: 'https://images.unsplash.com/photo-1757877255322-b9006e2296b3?q=80&w=600&auto=format&fit=crop',
    imageHint: 'cod fillets',
    dateListed: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
  },
  {
    id: '15',
    sellerId: 'seller1',
    name: 'Tilapia',
    weight: 85,
    price: 300,
    freshness: '1-2 Days',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1695299693952-4113f5682414?q=80&w=600&auto=format&fit=crop',
    imageHint: 'tilapia fish',
    dateListed: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    id: '16',
    sellerId: 'seller3',
    name: 'Mackerel',
    weight: 100,
    price: 420,
    freshness: 'Just Caught',
    imageUrl: 'https://images.unsplash.com/photo-1690375097427-78224325d7da?q=80&w=600&auto=format&fit=crop',
    imageHint: 'mackerel fish',
    dateListed: new Date().toISOString(),
  },
  {
    id: '17',
    sellerId: 'seller2',
    name: 'Sardine',
    weight: 150,
    price: 260,
    freshness: '1-2 Days',
    imageUrl: 'https://images.unsplash.com/photo-1577710943883-98eca3dd1b4e?q=80&w=600&auto=format&fit=crop',
    imageHint: 'sardine fish',
    dateListed: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
  },
  {
    id: '18',
    sellerId: 'seller1',
    name: 'Salmon',
    weight: 20,
    price: 1250,
    freshness: '3+ Days',
    imageUrl: 'https://images.unsplash.com/photo-1594767169572-04fe914b61de?q=80&w=600&auto=format&fit=crop',
    imageHint: 'salmon fish',
    dateListed: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
  },
  {
    id: '19',
    sellerId: 'seller3',
    name: 'Tuna',
    weight: 40,
    price: 820,
    freshness: '1-2 Days',
    imageUrl: 'https://images.unsplash.com/photo-1516741539888-96b4c96adf0c?q=80&w=600&auto=format&fit=crop',
    imageHint: 'tuna fish',
    dateListed: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    id: '20',
    sellerId: 'seller2',
    name: 'Pomfret',
    weight: 30,
    price: 980,
    freshness: 'Just Caught',
    imageUrl: 'https://images.unsplash.com/photo-1760560749248-308061f48097?q=80&w=600&auto=format&fit=crop',
    imageHint: 'pomfret fish',
    dateListed: new Date().toISOString(),
  },
];

const createPurchase = (listing: FishListing, quantity: number, buyerId: string, purchaseDate: string): Purchase => {
  const totalPrice = listing.price * quantity;
  const commission = totalPrice * 0.025;
  const tax = totalPrice * 0.05;
  const finalBill = totalPrice + commission + tax;

  return {
    id: `purchase-${Math.random().toString(36).substr(2, 9)}`,
    listing,
    buyerId,
    quantity,
    purchaseDate,
    totalPrice,
    commission,
    tax,
    finalBill,
  };
};

export const initialPurchases: Purchase[] = [
  createPurchase(initialFishListings[0], 10, 'buyer2', new Date(new Date().setDate(new Date().getDate() - 1)).toISOString()),
  createPurchase(initialFishListings[2], 20, 'buyer3', new Date().toISOString()),
  createPurchase(initialFishListings[4], 5, 'buyer1', new Date(new Date().setDate(new Date().getDate() - 3)).toISOString()),
  createPurchase(initialFishListings[6], 15, 'buyer4', new Date(new Date().setDate(new Date().getDate() - 2)).toISOString()),
  createPurchase(initialFishListings[8], 8, 'buyer2', new Date(new Date().setDate(new Date().getDate() - 1)).toISOString()),
  createPurchase(initialFishListings[10], 50, 'buyer5', new Date().toISOString()),
  createPurchase(initialFishListings[12], 12, 'buyer1', new Date(new Date().setDate(new Date().getDate() - 1)).toISOString()),
  createPurchase(initialFishListings[14], 25, 'buyer3', new Date(new Date().setDate(new Date().getDate() - 5)).toISOString()),
  createPurchase(initialFishListings[16], 30, 'buyer4', new Date().toISOString()),
  createPurchase(initialFishListings[18], 4, 'buyer5', new Date(new Date().setDate(new Date().getDate() - 3)).toISOString()),
];
