import type { FishListing } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const initialFishListings: FishListing[] = [
  {
    id: '1',
    sellerId: 'seller1',
    name: 'Tuna',
    weight: 50,
    price: 800,
    freshness: 'Just Caught',
    imageUrl: PlaceHolderImages[0].imageUrl,
    imageHint: PlaceHolderImages[0].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    id: '2',
    sellerId: 'seller2',
    name: 'Salmon',
    weight: 30,
    price: 1200,
    freshness: '1-2 Days',
    imageUrl: PlaceHolderImages[1].imageUrl,
    imageHint: PlaceHolderImages[1].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
  },
  {
    id: '3',
    sellerId: 'seller1',
    name: 'Sardine',
    weight: 100,
    price: 250,
    freshness: 'Just Caught',
    imageUrl: PlaceHolderImages[2].imageUrl,
    imageHint: PlaceHolderImages[2].imageHint,
    dateListed: new Date().toISOString(),
  },
  {
    id: '4',
    sellerId: 'seller3',
    name: 'Mackerel',
    weight: 80,
    price: 400,
    freshness: '1-2 Days',
    imageUrl: PlaceHolderImages[3].imageUrl,
    imageHint: PlaceHolderImages[3].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    id: '5',
    sellerId: 'seller2',
    name: 'Pomfret',
    weight: 40,
    price: 950,
    freshness: '3+ Days',
    imageUrl: PlaceHolderImages[4].imageUrl,
    imageHint: PlaceHolderImages[4].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
  },
];
