import type { FishListing } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const initialFishListings: FishListing[] = [
  {
    id: '1',
    sellerId: 'seller1',
    name: 'Tuna',
    weight: 50,
    price: 800,
    freshness: 'Just Caught',
    imageUrl: PlaceHolderImages[0].imageUrl,
    imageHint: PlaceHolderImages[0].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    id: '2',
    sellerId: 'seller2',
    name: 'Salmon',
    weight: 30,
    price: 1200,
    freshness: '1-2 Days',
    imageUrl: PlaceHolderImages[1].imageUrl,
    imageHint: PlaceHolderImages[1].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
  },
  {
    id: '3',
    sellerId: 'seller1',
    name: 'Sardine',
    weight: 100,
    price: 250,
    freshness: 'Just Caught',
    imageUrl: PlaceHolderImages[2].imageUrl,
    imageHint: PlaceHolderImages[2].imageHint,
    dateListed: new Date().toISOString(),
  },
  {
    id: '4',
    sellerId: 'seller3',
    name: 'Mackerel',
    weight: 80,
    price: 400,
    freshness: '1-2 Days',
    imageUrl: PlaceHolderImages[3].imageUrl,
    imageHint: PlaceHolderImages[3].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    id: '5',
    sellerId: 'seller2',
    name: 'Pomfret',
    weight: 40,
    price: 950,
    freshness: '3+ Days',
    imageUrl: PlaceHolderImages[4].imageUrl,
    imageHint: PlaceHolderImages[4].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
  },
  {
    id: '6',
    sellerId: 'seller1',
    name: 'Rohu',
    weight: 75,
    price: 350,
    freshness: 'Just Caught',
    imageUrl: PlaceHolderImages[6].imageUrl,
    imageHint: PlaceHolderImages[6].imageHint,
    dateListed: new Date().toISOString(),
  },
  {
    id: '7',
    sellerId: 'seller3',
    name: 'Catla',
    weight: 60,
    price: 320,
    freshness: '1-2 Days',
    imageUrl: PlaceHolderImages[7].imageUrl,
    imageHint: PlaceHolderImages[7].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
  },
  {
    id: '8',
    sellerId: 'seller2',
    name: 'Hilsa',
    weight: 25,
    price: 1500,
    freshness: 'Just Caught',
    imageUrl: PlaceHolderImages[8].imageUrl,
    imageHint: PlaceHolderImages[8].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    id: '9',
    sellerId: 'seller1',
    name: 'Kingfish (Surmai)',
    weight: 35,
    price: 1100,
    freshness: '1-2 Days',
    imageUrl: PlaceHolderImages[9].imageUrl,
    imageHint: PlaceHolderImages[9].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    id: '10',
    sellerId: 'seller3',
    name: 'Bombay Duck',
    weight: 90,
    price: 200,
    freshness: '3+ Days',
    imageUrl: PlaceHolderImages[10].imageUrl,
    imageHint: PlaceHolderImages[10].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString(),
  },
  {
    id: '11',
    sellerId: 'seller2',
    name: 'Anchovy',
    weight: 120,
    price: 180,
    freshness: 'Just Caught',
    imageUrl: PlaceHolderImages[11].imageUrl,
    imageHint: PlaceHolderImages[11].imageHint,
    dateListed: new Date().toISOString(),
  },
  {
    id: '12',
    sellerId: 'seller1',
    name: 'Red Snapper',
    weight: 45,
    price: 750,
    freshness: '1-2 Days',
    imageUrl: PlaceHolderImages[12].imageUrl,
    imageHint: PlaceHolderImages[12].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
  },
  {
    id: '13',
    sellerId: 'seller3',
    name: 'Grouper',
    weight: 55,
    price: 850,
    freshness: 'Just Caught',
    imageUrl: PlaceHolderImages[13].imageUrl,
    imageHint: PlaceHolderImages[13].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    id: '14',
    sellerId: 'seller2',
    name: 'Cod',
    weight: 65,
    price: 900,
    freshness: '3+ Days',
    imageUrl: PlaceHolderImages[14].imageUrl,
    imageHint: PlaceHolderImages[14].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
  },
  {
    id: '15',
    sellerId: 'seller1',
    name: 'Tilapia',
    weight: 85,
    price: 300,
    freshness: '1-2 Days',
    imageUrl: PlaceHolderImages[15].imageUrl,
    imageHint: PlaceHolderImages[15].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    id: '16',
    sellerId: 'seller3',
    name: 'Mackerel',
    weight: 100,
    price: 420,
    freshness: 'Just Caught',
    imageUrl: PlaceHolderImages[16].imageUrl,
    imageHint: PlaceHolderImages[16].imageHint,
    dateListed: new Date().toISOString(),
  },
  {
    id: '17',
    sellerId: 'seller2',
    name: 'Sardine',
    weight: 150,
    price: 260,
    freshness: '1-2 Days',
    imageUrl: PlaceHolderImages[17].imageUrl,
    imageHint: PlaceHolderImages[17].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
  },
  {
    id: '18',
    sellerId: 'seller1',
    name: 'Salmon',
    weight: 20,
    price: 1250,
    freshness: '3+ Days',
    imageUrl: PlaceHolderImages[18].imageUrl,
    imageHint: PlaceHolderImages[18].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
  },
  {
    id: '19',
    sellerId: 'seller3',
    name: 'Tuna',
    weight: 40,
    price: 820,
    freshness: '1-2 Days',
    imageUrl: PlaceHolderImages[19].imageUrl,
    imageHint: PlaceHolderImages[19].imageHint,
    dateListed: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    id: '20',
    sellerId: 'seller2',
    name: 'Pomfret',
    weight: 30,
    price: 980,
    freshness: 'Just Caught',
    imageUrl: PlaceHolderImages[4].imageUrl,
    imageHint: PlaceHolderImages[4].imageHint,
    dateListed: new Date().toISOString(),
  },
];
